# Generated by Django 3.2.9 on 2022-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
